# Generated by Django 5.1.6 on 2025-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Disponible"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=300, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos", verbose_name="Foto"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio"
            ),
        ),
    ]
